### ISSUE TITLE
Web server doesn't work any more

### ISSUE THREAD

**Issue by FakeEnd** [Tsedao/MultiRM#1]
I want to access processed sequence data, but disappointed to find web server crashed 
http://180.208.58.66/multirm/index.html

**Comment by Tsedao** [comment]
Hi, sorry for the crash down. Our web server had encountered unexpected hardware broken down and will still be unavailable for a while. If you require the original training sequences, please send us your e-mail. We will then send you the relevant dataset the following day.

**Comment by FakeEnd** [comment]
Thanks very much for your reply, my email is 201900301049@mail.sdu.edu.cn
