### ISSUE TITLE
Web Server is not accessible

### ISSUE THREAD

**Issue by RoyalMr6** [Tsedao/MultiRM#2]
Hello author, I found that the server www.xjtlu.edu.cn/biologicalsciences/multirm cannot be accessed. How can I obtain the processed sequence data?

**Comment by Tsedao** [comment]
Hi, sorry for the crash down. Our web server had encountered unexpected hardware broken down and will still be unavailable for a while. If you require the original training sequences, please send us your e-mail. We will then send you the relevant dataset the following day.

**Comment by RoyalMr6** [comment]
My email is hufangrui@emails.bjut.edu.cn , thanks very much for your help.
